apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: tutorial-energy-devops-1
  owner: tutorial-energy-devops-1
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/tutorial-energy-devops-1/multi-tenancy-gitops-apps.git
