apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgCta03A/o5mmevDVGVQDI1Q2W4bVhFZz+RhJUDbygoqRcPMCeC00XrtjfW1RHae6YyLmh8asqvwteezt7tApYQnPgZi0z67PFaXzLF2ojn3oQYcVB/yt5gE5m/KO/7Ni7ueQPVY+K8szFP4leAnuKT61md7gb8Z/BGiExWB30W4QC/REbyPYlX+fOesuK5KscipKkL+Aq4468KIKFIRE/4sfKJa+jr8GPFm3uft4BsER9WsP/7p4r5n2zV2YxuyoN6wZpstqW7Y3DPtPjvuDTniJtw0XupHBbkeM8S568sqIy9i9CEzs299nx+v5vX9UK5Wvwvvqvhu2yjqSDTca41ZC+RPEmqkaEFI8l+1psdIwBrLL4GmCU+rTnwqppcGrigJ6an976y7RCoyBWCWGti7Z/bWkJ6YRkXqLuDYppxnLuHVekzTFQdcaswArvk5UM2iDOgkA7k2NOZuw7FfQjjxmJkLi/71UhXnXRtyEWrzsMn4XJhfpPM5JYI2g27HmnVKYqPxnxZbwmyvwznjQ2dm2nwMDpLBcocwPFH0WQ6yTvzFRqXZiH0Xhvl7OutHuGl5EjBKCK+lhnEl+jWdPCbDHbyVlbGEVllDtadRQsT5v8LreeiMl6oyMbkUFg/HAdwWx2Iby6whYTuXtz+Tn/9IDYgXVOBuD5ibynya7IZHJVSDABmxngWsQ3Dn0wyFqAiV2mJxxdz0fvISkTJnK3w+DPXdOarnVUaUGHkAkwgcXYvCtKwsUa0I
    username: AgARhrwaVUDalpkDeysyB8WMb30Xia3H/i755XltDDmK2HAZmZ7pm+uOqtmXSXXxt+DWvvLhvZKgBtph+U9rv6z6Bdj2RRQENqwCTcwl1P1MoL2DcjW5kV0/57oH8jLqqzd/TXhNPqGoP3bmGyPiS+dHwuEX5maXtZOYyfKfGzNCvTY75vt+LFjHV+MrjgpX38rkByB4IhWsI/jK3NdHgfNNnfnEv8ma+GXmT6iyQlEDoYVUBurKzdVEJsp3sYWvrhJuK6LxFbli/o59jVYPTiC7+stU2mEZitmfSFv2RKs88wP8RpA0PgvXi8bd+ySCGDKDkbTWdWEqM7rkQtY4rIuqKTkkodsl/kmhZDIBPTA+R8V38UUx3Ec7AeVSpZekQ9JLBzM3SqL+6IKNQDBZ17/gqF7QjTjHgCegkgrxUrXHiJxvn/R9ASd/de1bt36ooXRUPOp1jj/+oU41izNcxgvALujnDBg2j5G3WNYBOopijmSb2X8Iw+x3E8OT2KvbZyUG1/Xz/sFS+iVmI4LbEqZLSWNIvRwzFGdiPzoCMZBq9vG4TKj1/hZYL+EjOKDXCGBNGu+BWHnNYScsANOBfBywd0Am/ZCMD3/xaSm5hJCb2nsq7uG57aY4YcJgmgxYtri6WG65u9LWbdWv2mCKpNmYq3r+WFFRUDYyOUPm0w748GDbx0EwgzcB5fOC8dnoE3kaE5S3Xfy45+E/3P+GPnyNgdh3juE=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

